"""Mise en concordance des tables avec modeles.py

Revision ID: aad5cabbce22
Revises: 3c9932f62b4c
Create Date: 2025-09-26 10:41:19.615458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad5cabbce22'
down_revision: Union[str, Sequence[str], None] = '3c9932f62b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
