"""Modification des colonnes de type Date

Revision ID: d4743031e5f2
Revises: aad5cabbce22
Create Date: 2025-09-26 11:04:48.117211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4743031e5f2'
down_revision: Union[str, Sequence[str], None] = 'aad5cabbce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_agregation', sa.Column(
        'date_a', sa.Date(), nullable=False))
    op.alter_column('t_agregation', 'type_appel',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'debut_periode',
                    existing_type=sa.TEXT(length=10),
                    type_=sa.Date(),
                    nullable=False)
    op.alter_column('t_agregation', 'fin_periode',
                    existing_type=sa.TEXT(length=10),
                    type_=sa.Date(),
                    nullable=False)
    op.alter_column('t_agregation', 'bat',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'bat_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'rub',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'rub_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'typ',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'typ_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'libelle',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'reference',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'nom_fournisseur',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.drop_column('t_agregation', 'date')
    op.alter_column('t_cles_repartition', 'base_rep',
                    existing_type=sa.TEXT(length=20),
                    type_=sa.String(length=20),
                    existing_nullable=True)
    op.add_column('t_base_data', sa.Column(
        'date_a', sa.Date(), nullable=False))
    op.alter_column('t_base_data', 'type_appel',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'debut_periode',
                    existing_type=sa.TEXT(length=10),
                    type_=sa.Date(),
                    nullable=False)
    op.alter_column('t_base_data', 'fin_periode',
                    existing_type=sa.TEXT(length=10),
                    type_=sa.Date(),
                    nullable=False)
    op.alter_column('t_base_data', 'bat',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'bat_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'rub',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'rub_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'typ',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'typ_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'libelle',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'reference',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'nom_fournisseur',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.drop_column('t_base_data', 'date')
    op.alter_column('t_lexique_bat', 'bat',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_lexique_bat', 'bat_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'batrub',
                    existing_type=sa.TEXT(length=6),
                    type_=sa.String(length=6),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'batrub_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'base_rep',
                    existing_type=sa.TEXT(length=20),
                    type_=sa.String(length=20),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'entites',
                    existing_type=sa.TEXT(length=30),
                    type_=sa.String(length=30),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'rgpt_entites',
                    existing_type=sa.TEXT(length=30),
                    type_=sa.String(length=30),
                    existing_nullable=True)
    op.alter_column('t_lexique_cles', 'groupe',
                    existing_type=sa.TEXT(),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_rub', 'rub',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_lexique_rub', 'rub_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_typ', 'typ',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_lexique_typ', 'typ_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_liste_groupes', 'groupe',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.add_column('t_originel_completee', sa.Column(
        'date_a', sa.Date(), nullable=False))
    op.alter_column('t_originel_completee', 'exercice',
                    existing_type=sa.TEXT(length=4),
                    type_=sa.String(length=4),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'periode_cloturee',
                    existing_type=sa.TEXT(length=1),
                    type_=sa.String(length=1),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'bat',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'rub',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'typ',
                    existing_type=sa.TEXT(length=3),
                    type_=sa.String(length=3),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'typ_tit',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'batrubtyp',
                    existing_type=sa.TEXT(length=10),
                    type_=sa.String(length=10),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'batrub',
                    existing_type=sa.TEXT(length=6),
                    type_=sa.String(length=6),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'libelle',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'reference',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'nom_fournisseur',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'rang_doublon',
                    existing_type=sa.TEXT(length=2),
                    type_=sa.String(length=2),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'groupe',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.drop_column('t_originel_completee', 'date')
    op.alter_column('t_parametres', 'indicateur',
                    existing_type=sa.TEXT(length=50),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    op.alter_column('t_parametres', 'valeur',
                    existing_type=sa.TEXT(length=20),
                    type_=sa.String(length=20),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_parametres', 'valeur',
                    existing_type=sa.String(length=20),
                    type_=sa.TEXT(length=20),
                    existing_nullable=True)
    op.alter_column('t_parametres', 'indicateur',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.add_column('t_originel_completee', sa.Column(
        'date', sa.TEXT(length=10), nullable=True))
    op.alter_column('t_originel_completee', 'groupe',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'rang_doublon',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'nom_fournisseur',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'reference',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'libelle',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'batrub',
                    existing_type=sa.String(length=6),
                    type_=sa.TEXT(length=6),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'batrubtyp',
                    existing_type=sa.String(length=10),
                    type_=sa.TEXT(length=10),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'typ_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'typ',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'rub',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'bat',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'periode_cloturee',
                    existing_type=sa.String(length=1),
                    type_=sa.TEXT(length=1),
                    existing_nullable=True)
    op.alter_column('t_originel_completee', 'exercice',
                    existing_type=sa.String(length=4),
                    type_=sa.TEXT(length=4),
                    existing_nullable=True)
    op.drop_column('t_originel_completee', 'date_a')
    op.alter_column('t_liste_groupes', 'groupe',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_typ', 'typ_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_typ', 'typ',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_lexique_rub', 'rub_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_rub', 'rub',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.alter_column('t_lexique_cles', 'groupe',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'rgpt_entites',
                    existing_type=sa.String(length=30),
                    type_=sa.TEXT(length=30),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'entites',
                    existing_type=sa.String(length=30),
                    type_=sa.TEXT(length=30),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'base_rep',
                    existing_type=sa.String(length=20),
                    type_=sa.TEXT(length=20),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'batrub_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_batrub', 'batrub',
                    existing_type=sa.String(length=6),
                    type_=sa.TEXT(length=6),
                    existing_nullable=True)
    op.alter_column('t_lexique_bat', 'bat_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_lexique_bat', 'bat',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.add_column('t_base_data', sa.Column(
        'date', sa.TEXT(length=10), nullable=True))
    op.alter_column('t_base_data', 'nom_fournisseur',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'reference',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'libelle',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'typ_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'typ',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'rub_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'rub',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'bat_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'bat',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_base_data', 'fin_periode',
                    existing_type=sa.Date(),
                    type_=sa.TEXT(length=10),
                    nullable=True)
    op.alter_column('t_base_data', 'debut_periode',
                    existing_type=sa.Date(),
                    type_=sa.TEXT(length=10),
                    nullable=True)
    op.alter_column('t_base_data', 'type_appel',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.drop_column('t_base_data', 'date_a')
    op.alter_column('t_cles_repartition', 'base_rep',
                    existing_type=sa.String(length=20),
                    type_=sa.TEXT(length=20),
                    existing_nullable=True)
    op.add_column('t_agregation', sa.Column(
        'date', sa.TEXT(length=10), nullable=True))
    op.alter_column('t_agregation', 'nom_fournisseur',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'reference',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'libelle',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'typ_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'typ',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'rub_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'rub',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'bat_tit',
                    existing_type=sa.String(length=50),
                    type_=sa.TEXT(length=50),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'bat',
                    existing_type=sa.String(length=3),
                    type_=sa.TEXT(length=3),
                    existing_nullable=True)
    op.alter_column('t_agregation', 'fin_periode',
                    existing_type=sa.Date(),
                    type_=sa.TEXT(length=10),
                    nullable=True)
    op.alter_column('t_agregation', 'debut_periode',
                    existing_type=sa.Date(),
                    type_=sa.TEXT(length=10),
                    nullable=True)
    op.alter_column('t_agregation', 'type_appel',
                    existing_type=sa.String(length=2),
                    type_=sa.TEXT(length=2),
                    existing_nullable=True)
    op.drop_column('t_agregation', 'date_a')
    # ### end Alembic commands ###
